---
- name: Chrony | Ensure /etc/chrony/conf.d/ directory exists
  ansible.builtin.file:
    path: /etc/chrony/conf.d/
    state: directory
    mode: '0755'

- name: Chrony | Remove the default pool line from chrony.conf
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: '^pool '
    state: absent
    backup: true
  when: chrony_remove_default_pool
  notify:
    - Restart chrony service

- name: Chrony | Deploy server pool list from template
  ansible.builtin.template:
    src: upstream_servers.conf.j2
    dest: /etc/chrony/conf.d/upstream_servers.conf
  when: chrony_upstream_servers
  notify:
    - Restart chrony service
