---
- name: Chrony | Install Chrony
  include_tasks: install.yml
    
- name: Chrony | Configure chrony server
  include_tasks: server.yml
  when: chrony_allowed_networks is defined

- name: Chrony | Configure chrony client
  include_tasks: client.yml
  when: chrony_allowed_networks is not defined
