---
- name: Chrony | Install Chrony
  ansible.builtin.include_tasks: install.yml

- name: Chrony | Configure chrony server
  ansible.builtin.include_tasks: server.yml
  when: chrony_allowed_networks is defined

- name: Chrony | Configure chrony client
  ansible.builtin.include_tasks: client.yml
  when: chrony_upstream_servers is defined
