---
- name: Chrony | Ensure /etc/chrony/conf.d/ directory exists
  file:
    path: /etc/chrony/conf.d/
    state: directory
    mode: '0755'

- name: Chrony | Create allowed_networks list, only hosts from these networks can connect to the Chrony server
  template:
    src: allowed_networks.conf.j2
    dest: /etc/chrony/conf.d/allowed_networks.conf
  when: chrony_allowed_networks

- name: Chrony | Restart Chrony
  systemd:
    name: "chrony"
    state: restarted
    enabled: yes
